// Ambient soundscapes shown in the Calm section. Each has a designed thumbnail
// in public/environments/{id}.webp (generated by scripts/gen-environments.mjs;
// swap in a real photo by replacing that file). Flip `available` as audio ships.

export interface Environment {
  id: string
  name: string
  description: string
  available: boolean
}

export const ENVIRONMENTS: Environment[] = [
  { id: 'cabin-rain', name: 'Gentle Rain on a Cabin Roof', description: 'Soft rain drumming on a wooden roof.', available: false },
  { id: 'ocean-waves', name: 'Ocean Waves', description: 'Slow swells rolling onto an open shore.', available: false },
  { id: 'rain-indoors', name: 'Rain Indoors', description: 'Rain at the window, warm and dry inside.', available: false },
  { id: 'rainforest', name: 'Rainforest', description: 'Dense canopy, dripping leaves, distant birds.', available: false },
  { id: 'thunderstorm', name: 'Thunderstorm', description: 'Rolling thunder over steady rainfall.', available: false },
  { id: 'riverside', name: 'Riverside', description: 'Cool water sliding over smooth stones.', available: false },
  { id: 'cafe', name: 'Café', description: 'Low chatter, clinking cups, a soft espresso hiss.', available: false },
  { id: 'public-infra', name: 'Ambient Public Infrastructure', description: 'The steady hum of stations and city flow.', available: false },
  { id: 'coastal-wind', name: 'Coastal Wind Rain Waves', description: 'Wind-driven rain over crashing surf.', available: false },
  { id: 'fire-crackling', name: 'Fire Crackling', description: 'A steady fire popping and crackling.', available: false },
  { id: 'heavy-waves', name: 'Heavy Waves', description: 'Powerful waves breaking on the rocks.', available: false },
  { id: 'morning-energy', name: 'Morning Energy', description: 'Birdsong and soft light to start the day.', available: false },
  { id: 'hvac-industrial', name: 'HVAC / Fans / Industrial', description: 'Even fan and machine hum for deep focus.', available: false },
  { id: 'aeroplane-cabin', name: 'Aeroplane Cabin', description: 'The smooth drone of a long-haul cabin.', available: false },
  { id: 'train-movement', name: 'Train Movement', description: 'The rhythmic clatter of rails.', available: false },
]

export const envThumb = (id: string) => `/environments/${id}.webp`
